/*
 Zaehlpixel 2.0 fuer planet-schule.de, (c) SWR
 commit: 0cd410b0d75a7082d18542f629839fe22d66a700
*/
window.planet_schule_de||(window.planet_schule_de={});window.planet_schule_de.webtrack||(window.planet_schule_de.webtrack={});
(function(){function r(b){for(var b=b.join("/").split("/"),a=[],c=[],d=0;d<b.length;d++)""!=b[d]&&(3>a.length?a:c).push(b[d]);0<c.length&&a.push(c.join("/"));return a.join("::")}function s(b,a,c,d,f,l){var g=0==l?"live":"clip";isFinite(f)&&isFinite(l)&&null!=f&&null!=l?(f=f.toFixed(0),l=l.toFixed(0),1>l&&(l="1")):(f="0",l="1");a in n||(n[a]=f);var C=n[a],j;a:{for(j=0;j<m.length;++j){var h=a.toLowerCase(),e="."+m[j][0];if(h.length>=e.length&&h.substr(h.length-e.length)==e){j=m[j][1];break a}}j="6"}xt_rm.apply(null,
[c+"&plyr=1",b,a,d,"","5",l,"rmp="+f+"&rmpf="+C+"&rmbufp=0","","1","int",g,"",j]);"move"==d&&(n[a]=f)}function o(b,a){if(a.dt){var c=(new Date).getTime();if(!t||c>=t+h.deadTime)t=c;else return}a.pi&&(p={});if(a.onepi&&!p[b])a.pi=!0,D&&(p={}),p[b]=!0;try{if(u(["PS_baseurl"])){var d=h.PS_baseurl+encodeURIComponent("/"+b),f;for(f in a)d+="&"+f+"="+encodeURIComponent(a[f]);d+="&ts="+(new Date).getTime();(new Image).src=d}}catch(l){}try{u(["IVW2_data"])&&a.pi&&iom.c(h.IVW2_data,1)}catch(g){}c=b;try{if(u(["ATI_basepath",
"ATI_subsite"])){var e=h.ATI_subsite,j=h.ATI_basepath;if(a.m){var k=c.split("/");":psvideo:"==k[1]&&(k.splice(0,2),c=k.join("/"),j="video");var n=r(["/Video-Start/Planet Schule",j,c]),m=r(["/Planet Schule",j,c]);a.pi&&xt_med.apply(null,["F",e,n]);a.t&x&&!(a.t&y)&&s(e,m,a.m,"pause",a.p,a.d);a.t&E&&s(e,m,a.m,"move",a.p,a.d);a.t&x&&a.t&y&&s(e,m,a.m,"play",a.p,a.d)}else{var o=r([j,c]);a.pi?xt_med.apply(null,["F",e,o]):xt_med.apply(null,["C",e,o,"A"])}}}catch(q){}}function F(b,a,c,d){var f=b+":"+a;f in
k||(k[f]=setTimeout(function(){delete k[f];o(a,c)},d))}function q(b,a,c){c.d=z(c.d);c.p=z(c.p);var d=b+"/"+a;d in v||(v[d]={a:!1,p:0,l:0});d=v[d];d.d=c.d;var f=(new Date).getTime()/1E3;if(d.a&&null!=d.p&&(d.p+=f-d.l,0<d.d&&d.p>d.d))d.p=d.d;d.l=f;var e=h.mediaTolerance/1E3,f=c.a,g=c.a!=d.a,e=null!=c.p&&null!=d.p&&!(c.p>=d.p-e&&c.p<=d.p+e);d.p=c.p;d.a=c.a;(g||e)&&o(a,{onepi:g&&f,m:b,t:f|g<<1|e<<2,p:c.p,d:c.d})}function z(b){b=parseFloat(b);return isNaN(b)?null:b}function A(b,a){for(var c=0;c<a.length;c++)g[a[c]]=
{f:e,h:function(a){o(a,b)}}}function e(b,a){return function(c){window.planet_schule_de.webtrack.trigger(b,a,c,{})}}function B(b){g[b+"State"]={f:function(a,b){return function(e,g,h,k){window.planet_schule_de.webtrack.trigger(a,b,e,{a:g,p:h,d:k})}},h:function(a,d){q(b,a,d)}};var a=b.substr(0,1).toUpperCase()+b.substr(1);g["play"+a]={f:e,h:function(a){q(b,a,{a:!0,p:null,d:null})}};g["pause"+a]={f:e,h:function(a){q(b,a,{a:!1,p:null,d:null})}};g["seek"+a]={f:e,h:function(){}}}function G(b){for(var a=
0;a<w.length;a++)b=w[a](b);return b}function u(b){for(var a=!1,c=0;c<b.length;c++)b[c]in h||(a=!0);return!a}var m=[["mp3",1],["wav",3],["aac",5],["mpg",6],["mpeg",6],["flv",7],["mp4",9],["avi",10],["rm",14],["mov",16],["ogg",17]],n={},t=null,p={},D=!0,k={},y=1,x=2,E=4,v={},g={};A({pi:!0,dt:!0},["page","choose","start","solved","failed"]);A({pi:!1,dt:!0},["action","funclick"]);g.mouseIn={f:e,h:function(b){F("mouseOver",b,{pi:!0,dt:!0},h.mouseOverDelay)}};g.mouseOut={f:e,h:function(b){b="mouseOver:"+
b;b in k&&(clearTimeout(k[b]),delete k[b])}};B("audio");B("video");g.fullscreenVideo={f:e,h:function(){}};g.fullscreenOffVideo={f:e,h:function(){}};var w=[],h={deadTime:100,mouseOverDelay:2E3,mediaTolerance:2E3};window.planet_schule_de.webtrack.config=function(b){for(i in b)h[i]=b[i]};window.planet_schule_de.webtrack.addmangler=function(b){w.push(b)};window.planet_schule_de.webtrack.create=function(b){var a={},c;for(c in g)a[c]=null===b?function(){}:g[c].f(c,b);return a};window.planet_schule_de.webtrack.trigger=
function(b,a,c,d){g[b]&&g[b].h(G(a+"/"+c),d)}})();
